version: "3.8"

services:
    nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: b_nginx-proxy
      restart: always
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./conf.d:/etc/nginx/conf.d
        - ./vhost.d:/etc/nginx/vhost.d:ro
        - ./logs:/var/log/nginx
        - ./cache:/var/lib/nginx/
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - /nginx-certs:/etc/nginx/certs:ro
      ports:
        - 80:80
        - 443:443
    nginx-letsencrypt:
      image: jrcs/letsencrypt-nginx-proxy-companion
      container_name: b_nginx-letsencrypt
      restart: always
      volumes_from:
        - nginx-proxy
      volumes:
        - ./vhost.d:/etc/nginx/vhost.d:ro
        - /nginx-certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
  default:
    external:
      name: b_nginx_network
