version: "3.8"

services:
    nginx: 
        image: jwilder/nginx-proxy:0.9.3-alpine
        container_name: b_nginx-proxy
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./conf.d:/etc/nginx/conf.d
            - ./vhost.d:/etc/nginx/vhost.d:ro
            - ./logs:/var/log/nginx
            - ./cache:/var/lib/nginx/
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
            - 443:443
networks:
  default:
    external:
      name: b_nginx_network